import { Platform, StyleSheet } from "react-native";
import { bold, fs, s } from "@/utils/scale";

export const styles = StyleSheet.create({
  // --- ONBOARD STYLES ---
  screen: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  contentContainer: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: s(24),
    paddingBottom: s(40),
    paddingTop: s(60),
  },
  topSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: fs(48),
    fontFamily: Platform.OS === "android" ? "Roboto-Black" : undefined,
    fontWeight: Platform.OS === "android" ? undefined : "900",
    color: "#ffffff",
    textShadowColor: "rgba(255, 255, 255, 0.8)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
    elevation: 5,
  },
  bottomSection: {
    width: "100%",
    alignItems: "center",
  },
  subtitle: {
    color: "#c300e1",
    fontSize: fs(14),
    marginBottom: s(16),
  },
  primaryButton: {
    width: "100%",
    backgroundColor: "#c300e1",
    paddingVertical: s(16),
    borderRadius: s(30),
    alignItems: "center",
    justifyContent: "center",
    marginBottom: s(12),
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: fs(16),
    fontWeight: "500",
  },
  secondaryButton: {
    width: "100%",
    backgroundColor: "transparent",
    borderColor: "#c300e1",
    borderWidth: 1,
    paddingVertical: s(16),
    borderRadius: s(30),
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#c300e1",
    fontSize: fs(16),
    fontWeight: "500",
  },

  // --- LOGIN STYLES ---
  scrollContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    padding: s(32),
    paddingVertical: s(50),
  },
  authTitle: {
    fontSize: fs(40),
    ...bold,
    color: "#ffffff",
    marginBottom: s(40),
    marginTop: Platform.OS === "ios" ? s(40) : s(20),
    alignSelf: "center",
  },
  label: {
    fontSize: fs(16),
    ...bold,
    color: "#ffffff",
    marginBottom: s(8),
    marginLeft: s(4),
  },
  authInput: {
    height: s(52),
    backgroundColor: "#ffffff",
    borderRadius: s(26),
    paddingHorizontal: s(20),
    fontSize: fs(16),
    color: "#333",
    marginBottom: s(12),
  },
  inputFocused: {
    backgroundColor: "#ffffff",
  },
  inputError: {
    borderWidth: 2,
    borderColor: "#D32F2F",
    marginBottom: s(4),
  },
  fieldErrorText: {
    color: "#ffddddff",
    fontSize: fs(12),
    marginBottom: s(12),
    marginLeft: s(16),
  },
  passwordRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: s(26),
    marginBottom: s(20),
    height: s(52),
  },
  passwordRowFocused: {
    backgroundColor: "#ffffff",
  },
  passwordInput: {
    flex: 1,
    height: "100%",
    paddingHorizontal: s(20),
    fontSize: fs(16),
    color: "#333",
  },
  eyeToggle: {
    paddingHorizontal: s(16),
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  authButton: {
    height: s(52),
    backgroundColor: "#ffffff",
    borderRadius: s(26),
    justifyContent: "center",
    alignItems: "center",
    marginTop: s(4),
    marginBottom: s(24),
  },
  authButtonDisabled: {
    opacity: 0.7,
  },
  authButtonText: {
    color: "#DD00FF",
    fontSize: fs(16),
  },
  forgotText: {
    fontSize: fs(15),
    color: "#ffffff",
    textAlign: "center",
    marginBottom: s(24),
  },
  dividerText: {
    fontSize: fs(15),
    color: "#ffffff",
    textAlign: "center",
    marginBottom: s(24),
  },
  googleButton: {
    height: s(52),
    backgroundColor: "#EBEBEB",
    borderRadius: s(26),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: s(12),
  },
  googleButtonText: {
    fontSize: fs(15),
    color: "#B902D6",
  },
  appleButton: {
    height: s(52),
    backgroundColor: "#EBEBEB",
    borderRadius: s(26),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: s(32),
  },
  appleButtonText: {
    fontSize: fs(15),
    color: "#B902D6",
  },
  signUpRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  signUpText: {
    fontSize: fs(15),
    color: "#ffffff",
  },
  signUpTextBold: {
    fontSize: fs(15),
    ...bold,
    color: "#ffffff",
  },
  errorBanner: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: s(10),
    borderLeftWidth: 4,
    borderLeftColor: "#D32F2F",
    padding: s(12),
    marginBottom: s(16),
  },
  errorText: {
    color: "#D32F2F",
    fontSize: fs(14),
  },
  successBanner: {
    backgroundColor: "transparent",
    borderRadius: 100,
    padding: s(12),
    marginBottom: s(16),
  },
  successText: {
    color: "#ffffff",
    fontSize: fs(14),
    textAlign: "center",
  },

  // --- SIGNUP STYLES ---
  signupInput: {
    height: s(52),
    backgroundColor: "#F0F0F0",
    borderRadius: s(26),
    paddingHorizontal: s(20),
    fontSize: fs(16),
    color: "#333",
    marginBottom: s(16),
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: s(24),
    marginTop: s(8),
    paddingHorizontal: s(4),
  },
  checkbox: {
    width: s(20),
    height: s(20),
    borderRadius: s(10),
    backgroundColor: "#ffffff",
    marginRight: s(10),
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: {
    backgroundColor: "#ffffff",
  },
  checkboxInner: {
    width: s(10),
    height: s(10),
    borderRadius: s(5),
    backgroundColor: "#DD00FF",
  },
  checkboxText: {
    color: "#ffffff",
    fontSize: fs(12),
    flex: 1,
    textAlign: "center",
  },
  checkboxTextBold: {
    ...bold,
  },
  signInButton: {
    height: s(52),
    borderWidth: 1,
    borderColor: "transparent",
    backgroundColor: "transparent",
    borderRadius: s(26),
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  dropdownContainer: {
    width: "80%",
    backgroundColor: "#ffffff",
    borderRadius: s(16),
    padding: s(16),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  dropdownTitle: {
    fontSize: fs(18),
    ...bold,
    color: "#333",
    marginBottom: s(16),
    textAlign: "center",
  },
  dropdownOption: {
    paddingVertical: s(14),
    paddingHorizontal: s(20),
    borderRadius: s(8),
  },
  dropdownOptionSelected: {
    backgroundColor: "rgba(142, 2, 184, 0.1)",
  },
  dropdownOptionText: {
    fontSize: fs(16),
    color: "#333",
    textAlign: "center",
  },
  dropdownOptionTextSelected: {
    color: "#8E02B8",
    ...bold,
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: "#E0E0E0",
    marginVertical: s(4),
  },
});
