import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    // --- ONBOARD STYLES ---
    screen: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    contentContainer: {
        flex: 1,
        justifyContent: "space-between",
        paddingHorizontal: 24,
        paddingBottom: 40,
        paddingTop: 60,
    },
    topSection: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    title: {
        fontSize: 48,
        fontWeight: "900",
        color: "#ffffff",
        textShadowColor: "rgba(255, 255, 255, 0.8)",
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 15,
        elevation: 5,
    },
    bottomSection: {
        width: "100%",
        alignItems: "center",
    },
    subtitle: {
        color: "#c300e1",
        fontSize: 14,
        marginBottom: 16,
    },
    primaryButton: {
        width: "100%",
        backgroundColor: "#c300e1",
        paddingVertical: 16,
        borderRadius: 30,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 12,
    },
    primaryButtonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "500",
    },
    secondaryButton: {
        width: "100%",
        backgroundColor: "transparent",
        borderColor: "#c300e1",
        borderWidth: 1,
        paddingVertical: 16,
        borderRadius: 30,
        alignItems: "center",
        justifyContent: "center",
    },
    secondaryButtonText: {
        color: "#c300e1",
        fontSize: 16,
        fontWeight: "500",
    },

    // --- LOGIN STYLES ---
    scrollContent: {
        flexGrow: 1,
        justifyContent: "flex-end",
        padding: 32,
        paddingVertical: 50,
    },
    authTitle: {
        fontSize: 40,
        fontWeight: "700",
        color: "#ffffff",
        marginBottom: 40,
        marginTop: Platform.OS === 'ios' ? 40 : 20,
        alignSelf: 'center',
    },
    label: {
        fontSize: 16,
        fontWeight: "700",
        color: "#ffffff",
        marginBottom: 8,
        marginLeft: 4,
    },
    authInput: {
        height: 52,
        backgroundColor: "#ffffff",
        borderRadius: 26,
        paddingHorizontal: 20,
        fontSize: 16,
        color: "#333",
        marginBottom: 12,
    },
    inputFocused: {
        backgroundColor: "#ffffff",
    },
    inputError: {
        borderWidth: 2,
        borderColor: "#D32F2F",
        marginBottom: 4,
    },
    fieldErrorText: {
        color: "#ffddddff",
        fontSize: 12,
        marginBottom: 12,
        marginLeft: 16,
    },
    passwordRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff",
        borderRadius: 26,
        marginBottom: 20,
        height: 52,
    },
    passwordRowFocused: {
        backgroundColor: "#ffffff",
    },
    passwordInput: {
        flex: 1,
        height: "100%",
        paddingHorizontal: 20,
        fontSize: 16,
        color: "#333",
    },
    eyeToggle: {
        paddingHorizontal: 16,
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    authButton: {
        height: 52,
        backgroundColor: "#ffffff",
        borderRadius: 26,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 4,
        marginBottom: 24,
    },
    authButtonDisabled: {
        opacity: 0.7,
    },
    authButtonText: {
        color: "#DD00FF",
        fontSize: 16,
    },
    forgotText: {
        fontSize: 15,
        color: "#ffffff",
        textAlign: "center",
        marginBottom: 24,
    },
    dividerText: {
        fontSize: 15,
        color: "#ffffff",
        textAlign: "center",
        marginBottom: 24,
    },
    googleButton: {
        height: 52,
        backgroundColor: "#EBEBEB",
        borderRadius: 26,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 12,
    },
    googleButtonText: {
        fontSize: 15,
        color: "#B902D6",
    },
    appleButton: {
        height: 52,
        backgroundColor: "#EBEBEB",
        borderRadius: 26,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 32,
    },
    appleButtonText: {
        fontSize: 15,
        color: "#B902D6",
    },
    signUpRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
    },
    signUpText: {
        fontSize: 15,
        color: "#ffffff",
    },
    signUpTextBold: {
        fontSize: 15,
        fontWeight: "700",
        color: "#ffffff",
    },
    errorBanner: {
        backgroundColor: "rgba(255,255,255,0.9)",
        borderRadius: 10,
        borderLeftWidth: 4,
        borderLeftColor: "#D32F2F",
        padding: 12,
        marginBottom: 16,
    },
    errorText: {
        color: "#D32F2F",
        fontSize: 14,
    },
    successBanner: {
        backgroundColor: "transparent",
        borderRadius: 100,
        // borderLeftWidth: 4,
        // borderLeftColor: "#2E7D32",
        padding: 12,
        marginBottom: 16,
    },
    successText: {
        color: "#ffffff",
        fontSize: 14,
        textAlign: "center",
    },

    // --- SIGNUP STYLES ---
    signupInput: {
        height: 52,
        backgroundColor: "#F0F0F0",
        borderRadius: 26,
        paddingHorizontal: 20,
        fontSize: 16,
        color: "#333",
        marginBottom: 16,
    },
    checkboxContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 24,
        marginTop: 8,
        paddingHorizontal: 4,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: "#ffffff",
        marginRight: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    checkboxChecked: {
        backgroundColor: "#ffffff",
    },
    checkboxInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#DD00FF",
    },
    checkboxText: {
        color: "#ffffff",
        fontSize: 12,
        flex: 1,
        textAlign: "center"
    },
    checkboxTextBold: {
        fontWeight: "700",
    },
    signInButton: {
        height: 52,
        borderWidth: 1,
        borderColor: "transparent",
        backgroundColor: "transparent",
        borderRadius: 26,
        justifyContent: "center",
        alignItems: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    dropdownContainer: {
        width: "80%",
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    dropdownTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 16,
        textAlign: "center",
    },
    dropdownOption: {
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    dropdownOptionSelected: {
        backgroundColor: "rgba(142, 2, 184, 0.1)",
    },
    dropdownOptionText: {
        fontSize: 16,
        color: "#333",
        textAlign: "center",
    },
    dropdownOptionTextSelected: {
        color: "#8E02B8",
        fontWeight: "bold",
    },
    dropdownDivider: {
        height: 1,
        backgroundColor: "#E0E0E0",
        marginVertical: 4,
    }
});
